### PR TITLE
strata-client: http client instead of ws for full node

### PR DESCRIPTION
**Pull request by voidash**
## Description

Full node bug where if sequencer is down, full node also has to go down is because of ws client needing restart after connection drop. Simple Fix to use http client instead of ws client

### Type of Change

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update
-   [ ] Refactor

## Checklist

-   [x] I have performed a self-review of my code.
-   [x] I have commented code where necessary.
-   [x] I have updated the documentation if needed.
-   [x] My changes do not introduce new warnings.
-   [x] I have added tests that prove my changes are effective or that my feature works.
-   [x] New and existing tests pass with my changes.

### CODE REVIEW

**Comment by storopoli** [comment]
Are we planning to have WS again in the future?

**Comment by delbonis** [comment]
This adds some overhead since we'd have to reestablish the connection on every request.  A better solution would be to use a connection pool that checks if the connection is still healthy when it goes to hand it out each time.  I've used the [deadpool](https://docs.rs/deadpool/latest/deadpool/) crate before, it's fairly easy to work with.  Could abstract out the calls we need to make behind a trait.

**Comment by delbonis** [comment]
But ehhh maybe this is fine for now.

**Comment by storopoli** [comment]
> This adds some overhead since we'd have to reestablish the connection on every request. A better solution would be to use a connection pool that checks if the connection is still healthy when it goes to hand it out each time. I've used the [deadpool](https://docs.rs/deadpool/latest/deadpool/) crate before, it's fairly easy to work with. Could abstract out the calls we need to make behind a trait.

https://alpenlabs.atlassian.net/browse/STR-518

**Review by delbonis — DISMISSED** [review]
Approving because this is only merging into a release branch.

**Comment by storopoli** [comment]
> Approving because this is only merging into a release branch.

Oh man! Where's Waldo moment. Could have included something about that in the PR description.
That was hard to notice.

**Comment by storopoli** [comment]
rebased

**Review by delbonis — APPROVED** [review]

**Pull request merged**
