### PR TITLE
ci: FREE CARGO-AUDIT!

### PR DESCRIPTION
**Pull request by storopoli**
## Description

Now that https://github.com/rustsec/rustsec/issues/1249 is closed, we are free to unpin `cargo-audit`.

### Type of Change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update
-   [ ] Refactor
-   [ ] New or updated tests
-   [x] Update Dependencies

## Checklist

-   [x] I have performed a self-review of my code.
-   [x] I have commented my code where necessary.
-   [x] I have updated the documentation if needed.
-   [x] My changes do not introduce new warnings.
-   [x] I have added tests that prove my changes are effective or that my feature works.
-   [x] New and existing tests pass with my changes.

## Related Issues

STR-601

### CODE REVIEW

**Comment by storopoli** [comment]
I think we're hitting https://github.com/rustsec/audit-check/issues/29 in CI failures

**Comment by Rajil1213** [comment]
> I think we're hitting https://github.com/rustsec/audit-check/issues/29 in CI failures

I think @prajwolrg has seen this issue before. I don't remember how we fixed it though. Re-running the CI job just to rule out any transient issues.

**Review by delbonis — DISMISSED** [review]

**Comment by prajwolrg** [comment]
> > I think we're hitting [rustsec/audit-check#29](https://github.com/rustsec/audit-check/issues/29) in CI failures
> 
> I think @prajwolrg has seen this issue before. I don't remember how we fixed it though. Re-running the CI job just to rule out any transient issues.

There was similar issue earlier. AFAIK we fixed it by locking to earlier version. @sapinb did most of the work here.

**Comment by storopoli** [comment]
Closing this... tried to run CI again and it's broken

**Comment by storopoli** [comment]
Blocked by https://github.com/rustsec/audit-check/issues/29

**Comment by storopoli** [comment]
Ok still broken!

**Comment by storopoli** [comment]
I'm closing this since rebasing `Cargo.lock` is a PITA.

**Pull request closed without merging**
