### PR TITLE
backport: CLI updates

### PR DESCRIPTION
**Pull request by storopoli**
## Description

Don't know how to proper fix #432.
So I'm opening a new one.

These are the needed patches for the `strata-cli` v0.1.0 release.

### Type of Change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update
-   [ ] Refactor
-   [ ] New or updated tests
-   [ ] Backport

## Checklist

-   [x] I have performed a self-review of my code.
-   [x] I have commented my code where necessary.
-   [x] I have updated the documentation if needed.
-   [x] My changes do not introduce new warnings.
-   [x] I have added tests that prove my changes are effective or that my feature works.
-   [x] New and existing tests pass with my changes.

### CODE REVIEW

**Comment by storopoli** [comment]
`cargo build`, `cargo build -p strata-cli`, `cargo clippy --workspace` and `cargo test` are all working.

**Review by sapinb — APPROVED** [review]

**Comment by storopoli** [comment]
It was supposed to be a squash merge no?

**Comment by delbonis** [comment]
@storopoli @sapinb I started a review in the other PR #432 but it was closed and this was merged before I could give feedback on it.

**Comment by storopoli** [comment]
The focus here was to bring all the `main` changes in the `strata-cli` to `releases/0.1.0` so that we could tag a release and have users installing the `strata-cli` from a tagged release and not from a branch.

**Pull request merged**
